import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import dynamic from 'next/dynamic'
import Footer from './components/Footer'

const DynamicNavBar = dynamic(() => import('@/app/components/NavBar'), {
})
 
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Pelis23',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">     
      <body className={inter.className}>
        <DynamicNavBar/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
